"""empty message

Revision ID: 47c5291f88d7
Revises: 
Create Date: 2018-06-14 21:03:01.476924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47c5291f88d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('nike_name', table_name='cm_users')
    op.drop_index('u_id', table_name='cm_users')
    op.drop_index('username', table_name='cm_users')
    op.drop_table('cm_users')
    op.drop_index('ix_cm_cookie_c_id', table_name='cm_cookie')
    op.drop_table('cm_cookie')
    op.drop_index('w_id', table_name='cm_website')
    op.drop_table('cm_website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cm_website',
    sa.Column('w_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('web_site_name', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=True),
    sa.PrimaryKeyConstraint('w_id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('w_id', 'cm_website', ['w_id'], unique=True)
    op.create_table('cm_cookie',
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('c_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('cookies_String', mysql.TEXT(collation='utf8_bin'), nullable=True),
    sa.Column('w_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['w_id'], ['cm_website.w_id'], name='cm_cookie_ibfk_1'),
    sa.PrimaryKeyConstraint('c_id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_cm_cookie_c_id', 'cm_cookie', ['c_id'], unique=False)
    op.create_table('cm_users',
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('u_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8_bin', length=20), nullable=True),
    sa.Column('password', mysql.VARCHAR(collation='utf8_bin', length=225), nullable=False),
    sa.Column('nike_name', mysql.VARCHAR(collation='utf8_bin', length=20), nullable=True),
    sa.PrimaryKeyConstraint('u_id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'cm_users', ['username'], unique=True)
    op.create_index('u_id', 'cm_users', ['u_id'], unique=True)
    op.create_index('nike_name', 'cm_users', ['nike_name'], unique=True)
    # ### end Alembic commands ###
