"""empty message

Revision ID: a1d616ded8b1
Revises: 9198750ec456
Create Date: 2018-06-28 19:09:50.492226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1d616ded8b1'
down_revision = '9198750ec456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cm_user', sa.Column('cookies_vt', sa.Integer(), nullable=True))
    op.add_column('cm_user', sa.Column('ip_proxy_vt', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cm_user', 'ip_proxy_vt')
    op.drop_column('cm_user', 'cookies_vt')
    # ### end Alembic commands ###
