"""empty message

Revision ID: ee869b997c4c
Revises: 07d13ab499ff
Create Date: 2018-06-18 14:32:54.683200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee869b997c4c'
down_revision = '07d13ab499ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cm_users', sa.Column('app_key', sa.String(length=225), nullable=False))
    op.add_column('cm_users', sa.Column('invitation_code', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'cm_users', ['app_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cm_users', type_='unique')
    op.drop_column('cm_users', 'invitation_code')
    op.drop_column('cm_users', 'app_key')
    # ### end Alembic commands ###
